export const CHANGE_TITLE_TEXT = 'CHANGE_TITLE_TEXT';
export const CHANGE_AUTHOR_TEXT = 'CHANGE_AUTHOR_TEXT';
export const CHANGE_DESCRIPTION_TEXT = 'CHANGE_DESCRIPTION_TEXT';
export const CHANGE_GENRE_TEXT = 'CHANGE_GENRE_TEXT';
export const CHANGE_RELEASE_DATE = 'CHANGE_RELEASE_DATE';
export const CHANGE_COVER_URL = 'CHANGE_COVER_URL';
export const CHANGE_ISBN_TEXT = 'CHANGE_ISBN_TEXT';
export const CHANGE_TOPICS_ARRAY = 'CHANGE_TOPICS_ARRAY';
export const CHANGE_BOOK_TEXT = 'CHANGE_BOOK_TEXT';

export const GET_LIST_OF_GENRES_SUCCESS = 'GET_LIST_OF_GENRES_SUCCESS';
export const GET_LIST_OF_GENRES_FAIL = 'GET_LIST_OF_GENRES_FAIL';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';