export const SHOW_SIGN_IN_FORM = 'SHOW_SIGN_IN_FORM';
export const SHOW_SIGN_UP_FORM = 'SHOW_SIGN_UP_FORM';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_RE_PASSWORD = 'CHANGE_RE_PASSWORD';
export const VALID_AUTH_PASSWORDS_FAIL = 'VALID_AUTH_PASSWORDS_FAIL';