export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';

export const GET_RECENT_BOOKS_REQUEST = 'GET_RECENT_BOOKS_REQUEST';
export const GET_RECENT_BOOKS_SUCCESS = 'GET_RECENT_BOOKS_SUCCESS';
export const GET_RECENT_BOOKS_FAIL = 'GET_RECENT_BOOKS_FAIL';

export const GET_BOOK_BY_ID_REQUEST = 'GET_BOOK_BY_ID_REQUEST';
export const GET_BOOK_BY_ID_SUCCESS = 'GET_BOOK_BY_ID_SUCCESS';
export const GET_BOOK_BY_ID_FAIL = 'GET_BOOK_BY_ID_FAIL';

export const GET_BOOKS_IN_CATEGORY_REQUEST = 'GET_BOOKS_IN_CATEGORY_REQUEST';
export const GET_BOOKS_IN_CATEGORY_SUCCESS = 'GET_BOOKS_IN_CATEGORY_SUCCESS';
export const GET_BOOKS_IN_CATEGORY_FAIL = 'GET_BOOKS_IN_CATEGORY_FAIL';