export const SHOW_COMMENTS = 'SHOW_COMMENTS';
export const SHOW_MORE_COMMENTS = 'SHOW_MORE_COMMENTS';
export const SHOW_COMMENT_BUTTONS = 'SHOW_COMMENT_BUTTONS';
export const CHANGE_COMMENT_TEXT = 'CHANGE_COMMENT_TEXT';
export const CHANGE_COMMENTS_OFFSET = 'CHANGE_COMMENTS_OFFSET';