export const CHANGE_BOOK_PAGE = 'CHANGE_BOOK_PAGE';
export const CHANGE_BOOK_PAGE_SIZE = 'CHANGE_BOOK_PAGE_SIZE';
export const CHANGE_END_OF_SWITCH = 'CHANGE_END_OF_SWITCH';
export const CHANGE_READ_OFFSET = 'CHANGE_READ_OFFSET';