export const CHANGE_SEARCH_INPUT_TEXT = 'CHANGE_SEARCH_INPUT_TEXT';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';

export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAIL = 'GET_SEARCH_RESULT_FAIL';

