export const CHANGE_SUBJECT_TEXT = 'CHANGE_SUBJECT_TEXT';
export const CHANGE_MESSAGE_TEXT = 'CHANGE_MESSAGE_TEXT';
export const RESET_INPUT_DATA = 'RESET_INPUT_DATA';
export const MAIL_TO_SUPPORT_SUCCESS = 'MAIL_TO_SUPPORT_SUCCESS';
export const MAIL_TO_SUPPORT_FAIL = 'MAIL_TO_SUPPORT_FAIL';